app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_admin:
    resource: "@AppBundle/Resources/config/routing/admin.yml"
    prefix:   /admin


app_product:
    resource: "@AppBundle/Resources/config/routing/producto.yml"
    prefix:   /product

app_new:
    resource: "@AppBundle/Resources/config/routing/noticia.yml"
    prefix:   /new

