app_product:
    resource: "@AppBundle/Resources/config/routing/producto.yml"
    prefix:   /product

app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

news_homepage:
    path:     /news
    defaults: { _controller: AppBundle:Noticias:index }

news_create:
    path:     /news/create
    defaults: { _controller: AppBundle:Noticias:create }

news_details:
    path:     /news/details/{id}
    defaults: { _controller: AppBundle:Noticias:details }

news_edit:
    path:     /news/edit/{id}
    defaults: { _controller: AppBundle:Noticias:edit }

news_update:
    path:     /news/update/{id}
    defaults: { _controller: AppBundle:Noticias:update }
    requirements: { _method: post|put }

news_delete:
    path:     /news/delete/{id}
    defaults: { _controller: AppBundle:Noticias:delete }
    requirements: { _method: post|delete }
